name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} R ${{ matrix.r-version }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-10.15, ubuntu-20.04 ]
        r-version: [ devel ]
    
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: bash run.sh '${{ matrix.r-version }}'
